### ISSUE TITLE
Decoration

### ISSUE THREAD

**Issue by Yatoom** [team-beta/furry-sansa#1]
Add flowers, crates, grass blades, tubes, random tools and other stuff to fill up the environment. Be creative, just like you did with the dancing robots!

**Comment by Runecreed** [comment]
![bench](https://cloud.githubusercontent.com/assets/9799758/5720571/3a388efc-9b26-11e4-878b-e0575ab011dd.png)
![crates](https://cloud.githubusercontent.com/assets/9799758/5720573/3a38c372-9b26-11e4-9297-e9e4aac8ebe1.png)
![flowers](https://cloud.githubusercontent.com/assets/9799758/5720574/3a38df4c-9b26-11e4-94e1-036960052338.png)
![shelf](https://cloud.githubusercontent.com/assets/9799758/5720575/3a3e275e-9b26-11e4-9482-dd5866340bb7.png)
![trashcan](https://cloud.githubusercontent.com/assets/9799758/5720572/3a38b2d8-9b26-11e4-9006-f5e1abff4762.png)

**Comment by Yatoom** [comment]
Needs some redrawing and placing within the level, but next to that, it is complete.
