### ISSUE TITLE
Restrictions on blocks?

### ISSUE THREAD

**Issue by Yatoom** [team-beta/furry-sansa#10]
Will we need any restrictions on blocks, like green blocks can only move, blue blocks can only solid/unsolid, red can only be resized, or can the game be played without too much overkill? Also, if we do that, won't we damage the sandbox-like system? (make sure programming still adds something, rather than a replacement of point and drag) Discuss with Twan/Kevin.

**Comment by Runecreed** [comment]
For gameplay and clarity it is nice to have this distinction, but seeing that we don't have many manipulations it suffices to just allow players to experiment with it.

also note that if it's possible to screw up a level we require a reset button.
