### ISSUE TITLE
Window/wall decoration house

### ISSUE THREAD

**Issue by Yatoom** [team-beta/furry-sansa#6]
The house in the third level should have a darker wooden background and maybe some windows, so that it really feels as if you are inside a house.

**Comment by Runecreed** [comment]
on it.

**Comment by Runecreed** [comment]
![building3_update](https://cloud.githubusercontent.com/assets/9799758/5702927/a41918cc-9a5f-11e4-9232-ab5aa068f127.png)

will this do?

**Comment by Yatoom** [comment]
Hey Kevin, the picture does not fit, and it is also not divisible by `32` ;) There is also some empty space around the image (especially at the top). The total picture should be something like `31*32 × 24*32`. Not sure if completely correct. Just a `32×32` background that could be tiled would also suffice (makes it easier to extend building too if needed).

The house is currently in the game. So, you can `world.main.changeLevel(3)` to it. Here are some screenshots:

![Imgur](http://i.imgur.com/l1HqoKR.png)
![Imgur](http://i.imgur.com/wzQircE.png)

**Comment by Runecreed** [comment]
I see - it's not scalable in the game engine?

I'll get right on it.

**Comment by Runecreed** [comment]
Alligned it now - We should get rid of unnessesary roof blocks that obsure it, allign an invisible wall so you can't jump trough the roof of the home.
![oki](https://cloud.githubusercontent.com/assets/9799758/5706237/66222ebc-9a7f-11e4-9ab7-c302773d9e98.png)

**Comment by Yatoom** [comment]
Sorry, house needed some more improvement ;)
![Imgur](http://i.imgur.com/IuhqaE9.png)

**Comment by Runecreed** [comment]
So i take it we don't want to have a 3D backdrop? Thats alright. I could drop your interior to my exterior but this works too. 
I would argue to not use the wooden tileset to fill up a roof though. That should be part of the background.
