### ISSUE TITLE
Machine?

### ISSUE THREAD

**Issue by Yatoom** [team-beta/furry-sansa#9]
I am not sure if the machine is still necessary. Because, instead of a wall glitch for the intro, it might be nicer to create a tunnel that is blocked by a block. Then, if you type help, an unknown entity will say `world.blocks.block_1.setSolidity(false)`, so that you already know what to do. Instead of a machine, we can also add info-panels (like in Pokémon) that give you a hint. Discuss this with Twan/Kevin.

**Comment by Runecreed** [comment]
you mean if you wish to alter a block that should become unsolid, if you do something like
world.blocks.block_1.help();

it will tell you the properties you can alter? 

i suppose that is enough.

maybe its a good idea to engrain the name of a block in the block itself with a text overlay attatched to it? explain it like the Robot can see the particulair objects he has power over
